name: Update current_sst.csv

on:
  push:
    branches: [ "main", "master" ]
  schedule:
    # Runs every day at 02:30 UTC (adjust as needed)
    - cron: '30 2 * * *'
  workflow_dispatch: {}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci || npm install

      - name: Generate current_sst.csv
        run: npm run update:sst

      - name: Commit changes if any
        run: |
          if git diff --quiet current_sst.csv; then
            echo "No changes to commit."
          else
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add current_sst.csv
            git commit -m "chore(ci): update current_sst.csv"
            git push
          fi


